name: jencap_server
description: Backend server for Jencap application
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^1.0.0
  mongo_dart: ^0.9.0
  dotenv: ^3.0.0
  json_annotation: ^4.8.0
  crypto: ^3.0.0
  jwt: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  test: ^1.24.0
  lints: ^2.0.0
